apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: kafka
  labels:
    app: {{ include "opensight-strimzi-deployment.fullname" . }}
    chart: {{ include "opensight-strimzi-deployment.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 5
  replicas: 3
  config:
    retentionMs: 7200000
    segmentBytes: 1073741824
